# Generated by Django 4.2.17 on 2025-01-02 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_leadsourceconfig_created_leadsourceconfig_modified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("int_array", "Array of Integers"),
                            ("json", "JSON"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.TextField()),
            ],
            options={"abstract": False,},
        ),
    ]
