# Generated by Django 4.2.17 on 2025-01-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="leadsourceconfig",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="saleslead",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="telecaller",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
