# Generated by Django 4.2.17 on 2025-01-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_config_created_alter_leadsourceconfig_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="config", name="created",),
        migrations.RemoveField(model_name="config", name="modified",),
        migrations.AddField(
            model_name="saleslead",
            name="filter_logic",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="config", name="value", field=models.JSONField(),
        ),
    ]
