# Generated by Django 4.2.17 on 2025-01-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_remove_config_created_remove_config_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleslead",
            name="filter_logic",
            field=models.TextField(blank=True, null=True),
        ),
    ]
