# Generated by Django 4.2.17 on 2025-01-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_saleslead_filter_logic"),
    ]

    operations = [
        migrations.RemoveField(model_name="saleslead", name="filter_logic",),
        migrations.AddField(
            model_name="leadsourceconfig",
            name="filter_logic",
            field=models.JSONField(default=dict),
        ),
    ]
