# Generated by Django 4.2.17 on 2025-01-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_remove_saleslead_filter_logic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsourceconfig",
            name="filter_logic",
            field=models.TextField(),
        ),
    ]
