# Generated by Django 4.2.17 on 2025-01-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_alter_leadsourceconfig_filter_logic"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleslead",
            name="source",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.leadsourceconfig",
            ),
        ),
    ]
